;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from my.el

(autoload 'my-visual-line-beginning-position "my"
"Get cursor point of visual line beginning position.

N is same meaning of `beginning-of-visual-line' argument.

(fn &optional N)" nil t)
(autoload 'my-beginning-of-smart-indented-line "my"
"Move curosr to beginning of indent.

Move to the beginning of the line if the cursor is at the beginning or middle of the indent." t)
(autoload 'my-other-window-reverse "my"
"Move before window, reverse behavior of `other-window'.

COUNT and ALL-FRAMES are same arguments of `other-window'.

(fn COUNT &optional ALL-FRAMES)" t)
(autoload 'my-revert-buffer "my"
"Run `revert-buffer-quick' and `normal-mode'.

This function is force avoid the problem that `font-lock' could become invalid
after running `revert-buffer-quick'.

AUTO-SAVE is same as 1st argument of `revert-buffer-quick'

(fn &optional AUTO-SAVE)" t)
(autoload 'my-insert-yen-sign "my"
"Insert YEN SIGN (U+00A5) character to cursor position." t)
(autoload 'my-insert-file-name "my"
"Insert current buffer's file name to cursor position.

NAME is string to target the string.
NAME is buffer to target the buffer file name.
NAME is other symbol to target the `current-buffer' file name.

Return string of file name.

(fn &optional NAME)" t)
(autoload 'my-insert-file-path "my"
"Insert current buffer's file path (full path) to cursor position.

NAME is string to target the string.
NAME is buffer to target the buffer file path.
NAME is other symbol to target the `current-buffer' file path.

Return string of file path.

(fn &optional NAME)" t)
(autoload 'my-fallback-font-family "my"
"Return a first matched avaliable font-family in FAMILIES.

Return nil to all FAMILIES are unavailable.

(fn &rest FAMILIES)" nil t)
(autoload 'my-set-fontset-font-safe "my"
"Return the result of `set-fontset-font' if don't cause error, or else nil.

ARGS are same arguments of `set-fontset-font'.

This feature seems to `car-safe' and `cdr-safe'.

(fn &rest ARGS)" nil t)

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
